// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Player struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	Skills    pgtype.JSONB `json:"skills"`
}

type PlayerSkill struct {
	PlayerID  uuid.UUID `json:"player_id"`
	SkillID   uuid.UUID `json:"skill_id"`
	CreatedAt time.Time `json:"created_at"`
	Value     int16     `json:"value"`
}

type PlayerTeam struct {
	PlayerID uuid.UUID `json:"player_id"`
	TeamID   uuid.UUID `json:"team_id"`
	JoinedAt time.Time `json:"joined_at"`
}

type Skill struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	Description string       `json:"description"`
}

type Sport struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Team struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
